dist: xenial
sudo: required

language: python
python:
  - "2.7"

install:
    # Dependencies
    - sudo apt-get -qq update
    - sudo pip install --upgrade -qq pip
    - sudo apt-get -qq install cdparanoia cdrdao flac libgirepository1.0-dev gir1.2-glib-2.0 libiso9660-dev libsndfile1-dev python-cddb sox swig libcdio-utils

    # Travis' Ubuntu is very old, libcdio needs to be compiled
    - wget https://ftp.gnu.org/gnu/libcdio/libcdio-2.0.0.tar.gz
    - tar -xvzf libcdio-2.0.0.tar.gz
    - pushd libcdio-2.0.0
    - ./configure
    - sudo make install
    - popd

    # Build bundled C utils
    - pushd src
    - sudo make install
    - popd
      #
    # Testing dependencies
    - sudo pip install tox-travis


script: tox
