sudo: required

language: bash

install:
    # Dependencies
    - sudo apt-get update -qq
    - sudo pip install --upgrade pip
    - sudo apt-get install -qq cdparanoia cdrdao gstreamer1.0-plugins-base gstreamer1.0-plugins-good libcdio-dev libiso9660-dev python-cddb python-gobject swig python-dev
    - sudo pip install musicbrainzngs pycdio

    # Testing dependencies
    - sudo apt-get install -qq python-gst-1.0
    - sudo pip install twisted

    # Checkout
    - ./autogen.sh

    # Building
    - ./configure
    - make

    # Installing
    - sudo make install

    # Check flacenc availability
    - sudo apt-get install -qq gstreamer1.0-tools
    - gst-inspect-1.0 flacenc

script:
    - python -m unittest discover
