sudo: required

language: bash

install:
    # Dependencies
    - sudo apt-get update -qq
    - sudo pip install --upgrade pip
    - sudo apt-get install -qq cdparanoia cdrdao gstreamer0.10-plugins-base gstreamer0.10-plugins-good libcdio-dev libiso9660-dev libsndfile1-dev python-cddb python-gobject swig python-dev python-xdg
    - sudo pip install musicbrainzngs pycdio

    # Testing dependencies
    - sudo apt-get install -qq gstreamer0.10-tools python-gst0.10
    - sudo pip install twisted

    # Checkout
    - ./autogen.sh

    # Building
    - ./configure
    - make

    # Installing
    - sudo make install

script:
    - python -m unittest discover
