dist: xenial
sudo: required

language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: false

cache: pip

env:
    - FLAKE8=false
    - FLAKE8=true

install:
    # Dependencies
    - sudo apt-get -qq update
    - pip install --upgrade -qq pip setuptools
    - sudo apt-get -qq install cdparanoia cdrdao flac gir1.2-glib-2.0 libcdio-dev libgirepository1.0-dev libiso9660-dev libsndfile1-dev sox swig libcdio-utils
    # Additional dependencies for PyGObject
    - sudo apt-get -qq install libglib2.0-dev libcairo2-dev libcairo2-dev libffi-dev

    # Build bundled C utils
    - cd src
    - sudo make install
    - cd ..

    # Installing
    - pip install .

script:
    - if [ ! "$FLAKE8" = true ]; then pip install .[test] && python -m unittest discover; fi
    - if [ "$FLAKE8" = true ]; then pip install .[lint] && flake8 --benchmark --statistics; fi
